---
role_name_check: 1
driver:
  name: podman
platforms:
  - name: instance
    # crun runtime lead to /proc issue in testing
    image: quay.io/speakintelnet/pinp-molecule:runc-latest
    privileged: true
    pre_build_image: true
    systemd: true
provisioner:
  name: ansible
  inventory:
    host_vars:
      instance:
        ansible_user: podman
verifier:
  name: ansible
